server:
  port: 8081
  
  
 #this is a service. It has to register itself to eureka server
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
#database/hibernate
spring: 
  datasource:
    username: root
    password: baba
    url: jdbc:mysql://localhost:3306/springdb
    
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    
#name for the service
  application:
    name: BOOK-SERVICE