server:
  port: 8082
  
spring:
  application:
    name: BOOK-VIEW-SERVICE
    
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
      
      
logging:
  level:
    root: info
    com: info
      