server:
    port: 8086
    
spring:
  application:
    name: CARTFEIGN-SERVICE
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
      
logging:
  level:
    root: info
    com: info
    