server:
  port: 8084
  
spring:
  application:
    name: BOOK-MVC-SERVICE
    
    
  mvc:
    view:
      prefix: WEB-INF/views/
      
      suffix: .jsp
    
#eureka:
#  client:
#    service-url:
#      default-zone: http:localhost:8761